source 'https://rubygems.org' do

  ruby '2.7.2'

  gem 'sinatra'
  gem 'webrick', '~> 1.7'

  group :test do
    gem 'capybara'
    gem 'rake' # not using
    gem 'rspec'
    gem 'rubocop', '0.79.0'
    gem 'selenium-webdriver' # do we need?
    gem 'simplecov', require: false
    gem 'simplecov-console', require: false
    gem 'timecop'
  end
end
